apiVersion: "v2"
appVersion: 0.0.6
name: catalogservice
description: "catalog application api service"
version: 0.0.6
sources:
- https://github.com/Azure/Mission-Critical
kubeVersion: ">=1.20.0"
maintainers:
- name: alwayson
  email: alwaysonappnet@microsoft.com