container:
  containerimage: "OVERWRITE.acr.io/alwayson/CatalogService:1234" # Container Image Name
  pullPolicy: "IfNotPresent" # Container Image Pull Policy. Using IfNotPresent to enable pod starts even if ACR cannot be reached and image was pulled on the node previously

workload:
  domainname: "OVERWRITE-cluster.eastus2.cloudapp.azure.com" # External Domain Name of the AKS cluster (used for Ingress)
  port: 8080 # Port of the container workload
  service:
    port: 80 # Service Port (not used for Ingress)
    type: "ClusterIP" # Service Type (default ClusterIP)

scale: # Horizontal Pod Autoscaler (HPA) configuration
  minReplicas: 3 # Min. number of replicas used for HPA
  maxReplicas: 20 # Max. number of replicas used for HPA

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "cert-manager-alwayson"

networkPolicy:
  enabled: true # Enable Network Policy (contains a default-deny policy)
  egressRange: "0.0.0.0/0" # CIDR range for allowed egress traffic

azure:
  frontdoorid: "" # Azure Front Door Header ID (blank = disabled)
  region: "East US 2"
  baseurl: "OVERWRITE.myalwaysonapp.net" # FQDN used by the Azure Front Door endpoint

healthservice:
  name: "healthservice-service" # name of the healthservice service in k8s
  port: 80
