# This file tells Grafana to add the Azure Monitor data source at provisioning time
# More info: https://grafana.com/docs/grafana/latest/datasources/azuremonitor/provisioning/

apiVersion: 1 # config file version

deleteDatasources:

datasources:
  - name: Azure Monitor
    type: grafana-azure-monitor-datasource
    access: proxy
    version: 1
    editable: false
    ordId: 1
    isDefault: true
    jsonData:
      azureAuthType: msi
      subscriptionId: ${AZURE_DEFAULT_SUBSCRIPTION}
      httpHeaderName1: 'Access-Control-Allow-Headers'
      httpHeaderName2: 'Access-Control-Allow-Origin'
    secureJsonData:
      httpHeaderValue1: 'origin, authorization, accept'
      httpHeaderValue2: 'https://afintgrafana-global-fd.azurefd.net/''