apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
  {{- if .Values.ingress.annotations }}
  {{ toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.workload.domainname | quote }}
    secretName: {{ .Values.workload.tlsSecret }} # shouldn't be changed as this might be used by other services
  rules:
  - host: {{ .Values.workload.domainname | quote }}
    http:
      paths:
      - path: /catalogservice/ # The path prefix MUST NOT overlap with any other ingress definition of another exposed service
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-service
            port:
              number: {{ .Values.workload.service.port | default 80 }}
