# Central configuration and versioning settings
# used for all pipelines
variables:
- name: 'riVariant' # Reference implementation variant - each repository should have its own identification. This value is surfaced to the UI.
  value: 'foundational-online'

- name: 'terraformVersion'    # Terraform Version
  value: '1.1.7'
- name: 'kubernetesVersion'   # kubernetes version used for aks clusters
  value: '1.22.6'
- name: 'helmVersion'         # helm package manager version
  value: 'v3.8.1'
- name: 'ingressNginxVersion' # nginx ingress controller helm chart version
  value: '4.0.19'
- name: 'certManagerVersion'  # cert-manager helm chart version
  value: 'v1.8.0'
- name: 'dotnetSdkVersion'    # dotnet sdk version
  value: '6.0.200'
- name: 'chaosMeshVersion'    #  chaos-mesh chart version
  value: '2.1.3'
- name: 'uiAppNodeVersion'    # nodejs version for the UI app
  value: '16.x'

- name: 'workloadNamespace'   # K8s namespace for workload deployment
  value: 'workload'
- name: 'chaosTestingNamespace'   # K8s namespace for chaos testing deployment
  value: 'chaos-testing'
- name: 'chaosStudioLocation'
  value: 'uksouth'
- name: 'chaosStudioApiVersion'
  value: '2021-08-11-preview'

# Docker image names and paths to the Dockerfiles for the different components
- name: 'catalogserviceDockerfile'
  value: 'AlwaysOn.CatalogService/Dockerfile'
- name: 'catalogserviceImageName'
  value: 'alwayson/catalogservice'
- name: 'backgroundprocessorDockerfile'
  value: 'AlwaysOn.BackgroundProcessor/Dockerfile'
- name: 'backgroundprocessorImageName'
  value: 'alwayson/backgroundprocessor'
- name: 'healthserviceDockerfile'
  value: 'AlwaysOn.HealthService/Dockerfile'
- name: 'healthserviceImageName'
  value: 'alwayson/healthservice'

# Embedded load testing configuration
# Make sure that these parameters are aligned with the loadtest-baseline.yaml
- name: 'loadTestNumberOfWorkerNodes' # number of worker nodes
  value: 10
- name: 'loadTestDurationInSeconds' # load test duration
  value: 300
- name: 'loadTestNumberOfUsers' # number of simulated users in the load test
  value: 500
- name: 'loadTestUserSpawnRate' # load test spawn rate users / per second
  value: 10

# Others
- name: 'smokeTestRetryCount' # How many times a request in the smoke tests is retried before declared as failed (retries HTTP response codes from 400-599 as well as issues like certificate errors)
  value: '20'
- name: 'smokeTestRetryWaitSeconds' # How long to wait between each retry of the smoke tests
  value: '60'
- name: 'skipComponentGovernanceDetection' # This is a Microsoft-specific setting. Having this in place ensures we don't create work items with CELA every time we use an open-source component
  value: 'true'
