# Central configuration and versioning settings
# used for all pipelines
variables:
- name: 'riVariant' # Reference implementation variant - each repository should have its own identification. This value is surfaced to the UI.
  value: 'foundational-online'

- name: 'terraformVersion'    # Terraform Version
  value: '1.3.5'
- name: 'kubernetesVersion'   # kubernetes version used for aks clusters
  value: '1.24.6'
- name: 'helmVersion'         # helm package manager version
  value: 'v3.10.2'
- name: 'ingressNginxVersion' # nginx ingress controller helm chart version
  value: '4.2.5'
- name: 'certManagerVersion'  # cert-manager helm chart version
  value: 'v1.9.1'
- name: 'dotnetSdkVersion'    # dotnet sdk version
  value: '6.0.400'
- name: 'chaosMeshVersion'    #  chaos-mesh chart version
  value: '2.3.1'
- name: 'uiAppNodeVersion'    # nodejs version for the UI app
  value: '18.x'
- name: 'testsNodeVersion'    # nodejs version used for smoketests / playwright
  value: '14.x'

- name: 'workloadNamespace'   # K8s namespace for workload deployment
  value: 'workload'
- name: 'ingressNamespace'    # K8s namespace for ingress deployment
  value: 'ingress-nginx'

# Docker image names and paths to the Dockerfiles for the different components
- name: 'catalogserviceDockerfile'
  value: 'AlwaysOn.CatalogService/Dockerfile'
- name: 'catalogserviceImageName'
  value: 'alwayson/catalogservice'
- name: 'backgroundprocessorDockerfile'
  value: 'AlwaysOn.BackgroundProcessor/Dockerfile'
- name: 'backgroundprocessorImageName'
  value: 'alwayson/backgroundprocessor'
- name: 'healthserviceDockerfile'
  value: 'AlwaysOn.HealthService/Dockerfile'
- name: 'healthserviceImageName'
  value: 'alwayson/healthservice'

# Microsoft Azure Load Test (MALT) configuration
- name: 'azureLoadTestApiVersion' # data plane
  value: '2022-06-01-preview'
- name: 'azureLoadTestEngineInstances'
  value: 2
- name: 'azureLoadTestVUsers'
  value: 100
- name: 'azureLoadTestDurationSeconds'
  value: 660
- name: 'azureLoadTestUserThreads'
  value: 500
- name: 'azureLoadTestBaseline'
  value: './.ado/pipelines/config/loadtest-baseline-normal.json'

# Chaos studio configuration
- name: 'chaosExperimentDurationSeconds'
  value: 180
- name: 'chaosStartDelaySeconds'
  value: 300
- name: 'chaosLoadTestBaseline'
  value: './.ado/pipelines/config/loadtest-baseline-chaos.json'

# Others
- name: 'smokeTestRetryCount' # How many times a request in the smoke tests is retried before declared as failed (retries HTTP response codes from 400-599 as well as issues like certificate errors)
  value: '20'
- name: 'smokeTestRetryWaitSeconds' # How long to wait between each retry of the smoke tests
  value: '60'
- name: 'skipComponentGovernanceDetection' # This is a Microsoft-specific setting. Having this in place ensures we don't create work items with CELA every time we use an open-source component
  value: 'true'
