# Central configuration settings
# used for PROD environment pipelines
variables:

# Resource prefix for this environment
- name:  'prefix'
  value: 'afprod'          # <===== CHANGE THIS! Must not be longer than 6 characters! Needs to be a unique prefix


# The first value in 'stampLocations' is the primary region used for global services.
# IMPORTANT! Changing the primary region (first value) is a BREAKING change and will destroy CosmosDB and Front Door.
- name: 'stampLocations'
  value: '["swedencentral", "brazilsouth"]' # Check which regions are valid. There is a list in /src/infra/README.md

- name: 'stampLocationsGrafana'
  value: '["eastus"]' # Check which regions are valid. There is a list in /src/infra/README.md

# Terraform state variables
- name:  'terraformResourceGroup'
  value: 'terraformstate-rg'         # <===== CHANGE THIS VALUE IF NEEDED
- name:  'terraformStorageAccount'
  value: '$(prefix)terraformstate'  # Needs to be a globally unique name

# Custom DNS name settings
- name: 'envDnsZoneRG'
  value: 'ao-dns-rg'            # <===== CHANGE THIS OR LEAVE THE VALUE BLANK
- name: 'envDomainName'
  value: 'shop.mission-critical.app'   # <===== CHANGE THIS OR LEAVE THE VALUE BLANK

# Other settings
- name:  'contactEmail'
  value: 'noreply@microsoft.com'  # <===== CHANGE THIS VALUE TO ONE OF YOUR REAL EMAIL ADDRESSES (OR A GROUP)!