apiVersion: "v2"
appVersion: 0.0.5
name: backgroundprocessor
description: "background processor worker"
version: 0.0.5
sources:
- https://github.com/Azure/Mission-Critical
kubeVersion: ">=1.20.0"
maintainers:
- name: alwayson
  email: alwaysonappnet@microsoft.com