apiVersion: "v2"
appVersion: 0.0.7
name: backgroundprocessor
description: "background processor worker"
version: 0.0.7
sources:
- https://github.com/Azure/Mission-Critical
kubeVersion: ">=1.21.0"
maintainers:
- name: alwayson
  email: alwaysonappnet@microsoft.com