name: LoadGenerator - CI

on:
  pull_request:
    paths:
      - "src/testing/userload-generator/AzureFunctions/**"
  workflow_dispatch:

env:
  DOTNET_VERSION: "6.0"

defaults:
  run:
    working-directory: "src/testing/userload-generator/AzureFunctions"

jobs:
  build-and-test-global:
    name: Build and test global
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Setup .NET Core ${{ env.DOTNET_VERSION }}"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Build the code"
        run: |
          cd GlobalOrchestrator
          dotnet build


  build-and-test-regional:
    name: Build and test regional
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Setup .NET Core ${{ env.DOTNET_VERSION }}"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Build the code"
        run: |
          cd RegionalLoadGenerator
          dotnet build
